name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest
      options: --user 1001
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Render JSON files
        run: |
          python -m pip install -r requirements.txt
          python render.py
          mkdir -p .build
      - name: Compile LaTex to PDF
        run: make
      - name: List generated files
        run: |
          ls -la .build/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-resume
          if-no-files-found: 'error'
          path: |
            index.html
            resume.tex
            .build/resume.pdf
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/v')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-resume
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./resume.pdf
          draft: false
          prerelease: false
