name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      options: --user 1001
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Render JSON files
        run: |
          python -m pip install -r requirements.txt
          python render.py

      - name: Auto commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Hugo Arganda
          author_email: hugo.arganda@gmail.com
          message: 'Autocommit generated files'
          add: 'index.html resume.tex'

      - name: Compile LaTex to PDF
        run: make

      # Upload just the PDF (adjust path if your Makefile outputs elsewhere)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-resume
          path: .build/resume.pdf     # <- make sure this matches your output
          if-no-files-found: error
          retention-days: 14          # optional; set what you want

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/v')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-resume
          path: .                     # download to repo root

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./resume.pdf              # this file now exists from the download step
          draft: false
          prerelease: false
