name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Render JSON files
        run: |
          python -m pip install -r requirements.txt
          python render.py
      - name: Compile LaTex to PDF
        run: make
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-resume
          path: |
            .build/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rendered_html
          path: |
            index.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rendered_tex
          path: |
            resume.tex
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/v')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: pdf-resume
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./resume.pdf
          draft: false
          prerelease: false
