name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile LaTex to PDF
        run: make
      - name: Set env variables
        run: |
          sudo apt-get install -y jq
          FILE_NAME=$(jq -r '.basics.name' resume.json | sed -r 's/ /_/g')
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
      - shell: bash
        run: |
          cp .build/resume.pdf ${{ env.FILE_NAME }}.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.FILE_NAME }}.pdf
          draft: false
          prerelease: false
